version: '3.0'
services:
  backend:
    build:
      context: ./tic-tac-toe
      dockerfile: ./Dockerfile
    container_name: ttt_backend
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build:
      context: ./ttt_front
      dockerfile: ./Dockerfile
    container_name: ttt_front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
